### PR TITLE
refactor(re-arranging files to avoid unecessary react dependency in most of the library): moved all

### LINKED ISSUE #26: Dependencies of react
I was trying to use this amazing tool with [require-universal-module](https://github.com/faceyspacey/require-universal-module) in an no react environment. but apparently this library is react dependant.

```log
ERROR in (webpack)-flush-chunks/dist/createApiWithCss.js
    Module not found: Error: Can't resolve 'react' in 'C:\Users\bernardosunderhus\Desktop\pextra\node_modules\webpack-flush-chunks\dist'
     @ (webpack)-flush-chunks/dist/createApiWithCss.js 8:13-29
     @ (webpack)-flush-chunks/dist/flushChunks.js
     @ ./src/node/index.js
```

Is there any plans to make this work without this dependency?

### PR DESCRIPTION
**Pull request by sunderhus**
The only method that relies on react are the ones provided by the createApiWithCss and the only
method that depends on createApiWithCss is the flushChunks. By separating flushChunks from the rest
of the methods I'm making this library a little bit more independent and more  like a universal
solution to the chunks problems

closes #26

### CODE REVIEW

**Comment by BernardoS** [comment]
Didn't know if the PR should be to master of to another branch @faceyspacey so I did to master anyway. Let me know if the re-arranging is suited, I'd love to use this in my next project

**Comment by faceyspacey** [comment]
solid work.

can you remove the duplication of Flow types. Perhaps put them all in their own file (including createApiWithCss file). 

and then lastly add a note somewhere in the readme (around the "low level api" section) regarding importing directly if you want to use outside of React.

**Comment by BernardoS** [comment]
I was actually thinking in a way to break the `createApiWithCss`, so that I can still use it without the react dependency. Because afterall,
```js
{ 
  js: { toString: [Function: toString] },
  styles: { toString: [Function: toString] },
  css: { toString: [Function: toString] },
  scripts: [],
  stylesheets: [],
  publicPath: '',
  outputPath: undefined,
  cssHashRaw:
   { app: '/css/vendors.01c3d969670d86f14de5c55eccaa7507.css',
     Notifications: '/css/Notifications.b3fe24904851739e2b2590d81692f605.css',
     Sensors: '/css/Sensors.545ecf3b0e2b4f977dec19071ad5dec8.css',
     Stream: '/css/Stream.7999ca629a44add0721492c63e9278c8.css',
     Sensor: '/css/Sensor.545ecf3b0e2b4f977dec19071ad5dec8.css' },
  cssHash: { toString: [Function: toString] } 
}
```

that's the real deal!!!! I just have to make it independent of those JS, Css, Styles and CssHassh!

**Comment by faceyspacey** [comment]
is aliasing `react` in webpack not an option? Alias it to `null` or an object since it simply won't be used.

I'm honestly a little afraid of this PR. My time is very limited right now, and I really should take a closer look before merging it.

Another technique by the way is we don't require/import React the regular way. Instead we do it "weakly" like is done in react-universal-component:

https://github.com/faceyspacey/react-universal-component/blob/master/src/utils.js#L24


```js
export const requireReact = (): ?any => {
  if (!isWebpack(){
    return module.require('react')
  }

  return __webpack_require__(require.resolveWeak('react'))
}
```

That should work but I've never "weakly" required anything except userland modules.

Then you just call `requireReact` in the react-based functions that need it.

I'd really try just aliasing webpack for now--cuz even this scares me a bit. It's just a non-standard thing I'm not sure want to introduce here. I mean i do, but I just need to be 100% sure it's not going to cause anyone any problems.

**Comment by BernardoS** [comment]
I **am** aliasing it for now. It is an option for me, I'm just trying to find a more elegant and definite solution. Time is no problem, I'll be using my fork in my project for now, you can take your time! And thx for the references.

**Comment by BernardoS** [comment]
It seems to be working fine the weak strategy. But the CI seems to be having troubles with it in the stable version of node, which is funny, cause my environment is using node v6.11.2  and all tests are ok. I'll dig into this later

**Comment by faceyspacey** [comment]
hmmm...

exciting to know u got the weak stuff working in general.

as for the flow type, perhaps just a weaker type solves that.

either way, this is very interesting. cool stuff. we're gonna be able to do a lot of cool things with the "weak" requiring. ive actually had some things planned for it for a while, so it's nice to know it works as expected.

**Pull request closed without merging**
