### PR TITLE
fix($browser): reverse css order. fixes #7

### LINKED ISSUE #7: Stylesheets in reversed order
CSS ordering is reversed as it would be if the files were not split into separate files.

```html
<head>
  <link rel='stylesheet' href='/static/0.css' />
  <link rel='stylesheet' href='/static/7.css' />
  <link rel='stylesheet' href='/static/main.css' />
</head> 
```

The CSS files should be reversed:

```html
<head>
  <link rel='stylesheet' href='/static/main.css' />
  <link rel='stylesheet' href='/static/7.css' />
  <link rel='stylesheet' href='/static/0.css' />
</head> 
```

### PR DESCRIPTION
**Pull request by chrisblossom**
#7

### CODE REVIEW

**Comment by faceyspacey** [comment]
it failed because i recently changed my NPM password, which means I need to change all my NPM tokens unfortunately. 

...i was looking at the snapshots and in the commit and I realized that the chunks were in the correct order. It was just the main.css that needs to go first. ...Im going to look into how to best handle that.

**Comment by faceyspacey** [comment]
http://blog.npmjs.org/post/161515829950/credentials-resets

...this is super annoying. i got a lot of packages i gotta change the tokens of for travis to work.

**Comment by faceyspacey** [comment]
the token is updated. I restarted the build in Travis, and it's now re-running here as you can see above. 

...so basically ur commit will handle the most common use case. To make it do it fully requires this:

*src/flushChunks.js:*
```js
const flushChunks = (stats: Stats, isWebpack: boolean, opts: Options = {}) => {
  const beforeEntries = opts.before || defaults.before
  const jsBefore = filesFromChunks(beforeEntries, stats.assetsByChunkName)

  const files = opts.chunkNames
    ? filesFromChunks(opts.chunkNames, stats.assetsByChunkName)
    : flush(opts.moduleIds || [], stats, opts.rootDir, isWebpack)

  const afterEntries = opts.after || defaults.after
  const jsAfter = filesFromChunks(afterEntries, stats.assetsByChunkName)

  return createApiWithCss(
    [
      ...jsBefore,
      ...files,
      ...jsAfter
    ], [
      ...jsBefore, // likely nothing in here, but if so: bootstrap.css, vendor.css, etc
      ...jsAfter.reverse(), // main.css, someElseYouPutBeforeMain.css, etc
      ...files // correct incrementing order already
    ],
    stats.publicPath,
    opts.outputPath
  )
}
```

*src/createApiWithCss.js:*
```js
export default (
  files: Array<string>,
  filesOrderedForCss: Array<string>,
  publicPath: string,
  outputPath: ?string
): Api => {
  const regex = getJsFileRegex(files)
  const scripts = files.filter(file => isJs(regex, file))
  const stylesheets = filesOrderedForCss.filter(isCss)
  // ...
```

...i just wrote that quick. if u decide to keep going with this, check the snapshots to make sure it got it correct. To really check it u'll have to put other entries in the `before` and `after` options (and write tests).

**Comment by faceyspacey** [comment]
...actually the build issue seems to be the package i built to post lint error count, flow errors, test counts, etc, doesn't seem to be working for you. Github isn't authenticated to post statuses, which really shouldnt be an issue since it should use my GH_TOKEN. ...im just gonna complete this and push to your PR, and see if GH authenticates. ...if it doesn't, i gotta figure out how to make other people submitting PRs not break it.

**Comment by faceyspacey** [comment]
...if u add me to your fork, i can push my changes to this same PR. go to:

https://github.com/chrisblossom/webpack-flush-chunks/settings/collaboration

**Comment by chrisblossom** [comment]
I won't be able to fix this right now, but can late tomorrow. You can close this if you want and push the changes sooner than later if you want.

Also, I wasn't sure if it counted as a breaking change.

**Comment by faceyspacey** [comment]
im saying i did it. ...just add me as a collaborator to your fork via the above link. and i'll push to this PR, which will/should give u credit for it.

**Comment by faceyspacey** [comment]
...for whatever reason even when i pushed to your branch it couldn't authenticate with github. i'll have to look into that.

either way, i pushed and published the changes. run `npm upgrade webpack-flush-chunks`. thanks for the find!

**Pull request closed without merging**
